# -*- coding: utf-8 -*-
from . import pos_branch
from . import pos_order_type
from . import res_partner
from . import res_partner_category
from . import res_partner_credit
from . import res_partner_credit_program
from . import product_product
from . import product_pricelist
from . import product_pricelist_item
from . import pos_config
from . import pos_session
from . import pos_session_management
from . import res_config_settings
from . import sale_order
from . import sale_order_line
from . import pos_order
from . import pos_order_line
from . import pos_payment_method
from . import pos_printer
from . import pos_product_bom
from . import pos_payment
from . import stock_location
from . import stock_lot
from . import purchase_order
from . import product_barcode
from . import product_cross_sell_group
from . import product_pack
from . import product_uom_price
from . import stock_picking
from . import res_users
from . import account_move
from . import hr_employee
from . import big_data
from . import ir_rule
from . import account_bank_statement_line